services:
  php:
    image: tugboatqa/php:7.3-apache
    default: true
    depends: mysql
    commands:
      init:
        - apt update
        - apt install -y software-properties-common curl build-essential imagemagick
        - curl -sL https://deb.nodesource.com/setup_12.x | bash -
        - apt install -y nodejs
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - apt update
        - apt install yarn
        - docker-php-ext-install pdo pdo_mysql imagick curl openssl mbstring bcmath json xml
        - a2enmod headers rewrite
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"
        - mkdir -p storage/app/public
        - mkdir -p storage/app/public/elephpants
        - mkdir -p storage/framework/cache
        - mkdir -p storage/framework/sessions
        - mkdir -p storage/framework/testing
        - mkdir -p storage/framework/views
        - mkdir -p storage/logs
        - touch storage/logs/laravel.log
        - chown -R www-data storage bootstrap/cache
        - chmod -R 744 storage bootstrap/cache
      build:
        - rm -f .env
        - cp .tugboat/.env.staging ./.env
        - chown www-data .env
        - echo "APP_URL=$TUGBOAT_SERVICE_URL" >> .env
        - echo "MAIL_HOST=$TUGBOAT_SMTP" >> .env
        - composer install -n --prefer-dist --no-progress --no-suggest
        - yarn install
        - php artisan key:generate
        - php artisan cache:clear
        - php artisan migrate:fresh --seed
        - yarn run dev
  mysql:
    image: tugboatqa/mysql:5.7
