services:
  php:
    image: tugboatqa/php:apache
    default: true
    commands:
      init:
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"
      update:
        - composer install
        - php artisan migrate
        - php artisan db:seed
  mysql:
    image: tugboatqa/mysql:5.7
