services:
  php:
    image: tugboatqa/php:apache
    default: true
    commands:
      init:
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"
      update:
        - php "${TUGBOAT_ROOT}/artisan" migrate
        - php "${TUGBOAT_ROOT}/artisan" db:seed
  mysql:
    image: tugboatqa/mysql:5.7
